version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/rust:1.32.0-stretch

jobs:
  build:
    docker:
      - image: circleci/rust:1.32.0-stretch
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          name: "Cargo.lock cache"
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: build-container
          command: docker build -t dark-cli .
      - run:
          name: Build all targets
          command: docker run -it dark-cli build --release
      - persist_to_workspace:
          root: "."
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/x86_64-pc-windows-gnu/.fingerprint
            - target/x86_64-pc-windows-gnu/build
            - target/x86_64-pc-windows-gnu/deps
            - target/x86_64-apple-darwin-gnu/.fingerprint
            - target/x86_64-apple-darwin-gnu/build
            - target/x86_64-apple-darwin-gnu/deps
            - target/x86_64-unknown-linux-musl/.fingerprint
            - target/x86_64-unknown-linux-musl/build
            - target/x86_64-unknown-linux-musl/deps
            - target/x86_64-unknown-linux-gnu/.fingerprint
            - target/x86_64-unknown-linux-gnu/build
      - save_cache:
          name: "Cargo.lock cache"
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

  test:
    docker:
      - image: circleci/rust:1.32.0-stretch
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          name: "Cargo.lock cache"
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: build-container
          command: docker build -t dark-cli .
      - run:
          name: Build all targets
          command: docker run -it dark-cli build --release
      - persist_to_workspace:
          root: "."
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/x86_64-pc-windows-gnu/.fingerprint
            - target/x86_64-pc-windows-gnu/build
            - target/x86_64-pc-windows-gnu/deps
            - target/x86_64-apple-darwin-gnu/.fingerprint
            - target/x86_64-apple-darwin-gnu/build
            - target/x86_64-apple-darwin-gnu/deps
            - target/x86_64-unknown-linux-musl/.fingerprint
            - target/x86_64-unknown-linux-musl/build
            - target/x86_64-unknown-linux-musl/deps
            - target/x86_64-unknown-linux-gnu/.fingerprint
            - target/x86_64-unknown-linux-gnu/build
            - target/x86_64-unknown-linux-gnu/deps
      - save_cache:
          name: "Cargo.lock cache"
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/x86_64-pc-windows-gnu/.fingerprint
            - target/x86_64-pc-windows-gnu/build
            - target/x86_64-pc-windows-gnu/deps
            - target/x86_64-apple-darwin-gnu/.fingerprint
            - target/x86_64-apple-darwin-gnu/build
            - target/x86_64-apple-darwin-gnu/deps
            - target/x86_64-unknown-linux-musl/.fingerprint
            - target/x86_64-unknown-linux-musl/build
            - target/x86_64-unknown-linux-musl/deps
            - target/x86_64-unknown-linux-gnu/.fingerprint
            - target/x86_64-unknown-linux-gnu/build
            - target/x86_64-unknown-linux-gnu/deps
      - run:
          name: Run all tests
          command: docker run -it dark-cli test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - build

        # we need an actual deploy here
